# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: "Group Project"
email: ""
description: "Group Project"
url: "https://coursereps.github.io"
baseurl: "/ECEN489-Spring2015"
github_username: "BenitoRamirezJr"
# Build settings
markdown: kramdown
