# Site settings
exclude: [".gitignore", "README.md", "Gemfile"]
title: "ScoutOut"
email: ""
description: "Location-Specific Friend Analytics"
url: "http://coursereps.github.io"
baseurl: "/ECEN489-Spring2015"
github_username: "BenitoRamirezJr"
# Build settings
markdown: kramdown
